name: Sync Notion to GitHub
on:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Sync Notion to GitHub
        uses: novuhq/notion-to-github-sync-action@latest
        with:
          notion-integration-key: ${{ secrets.NOTION_TOKEN }}
          github-access-token: ${{ secrets.GITHUB_TOKEN }}
          repo-owner: chesterdefends
          repo: red-ops-labs
          branch: main
          docs-path: ./notion-docs/
